/**
 * Auto-Generate Deadlines — DB Orchestrator
 *
 * Bridges the pure deadline-generator with the database. When a task is
 * completed, this function:
 *
 * 1. Fetches existing deadline keys for the case (deduplication)
 * 2. Calls generateDeadlines() (pure, no side effects)
 * 3. For each generated deadline:
 *    a. Inserts into `deadlines` table (label, consequence, auto_generated)
 *    b. Creates reminders at -7d, -3d, -1d (skips dates in the past)
 *    c. Writes audit event to `task_events`
 *    d. Creates in-app notification for the case owner
 */

import { SupabaseClient } from '@supabase/supabase-js'
import { generateDeadlines } from './deadline-generator'

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface AutoGenerateInput {
  taskKey: string
  caseId: string
  completedAt: string
  taskMetadata: Record<string, unknown>
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export async function autoGenerateDeadlines(
  supabase: SupabaseClient,
  input: AutoGenerateInput
): Promise<void> {
  // 1. Fetch existing deadline keys for this case (deduplication)
  const { data: existingDeadlines } = await supabase
    .from('deadlines')
    .select('key')
    .eq('case_id', input.caseId)

  const existingKeys = (existingDeadlines ?? []).map(
    (d: { key: string }) => d.key
  )

  // 2. Generate deadlines via pure function
  const deadlines = generateDeadlines({
    taskKey: input.taskKey,
    caseId: input.caseId,
    completedAt: input.completedAt,
    taskMetadata: input.taskMetadata ?? {},
    existingDeadlineKeys: existingKeys,
  })

  if (deadlines.length === 0) return

  // 3. Fetch case owner once (used for notifications)
  const { data: caseData } = await supabase
    .from('cases')
    .select('user_id')
    .eq('id', input.caseId)
    .single()

  // 4. For each deadline: insert + reminders + audit + notification
  for (const deadline of deadlines) {
    // --- Insert deadline row ---
    const { data: inserted, error: insertError } = await supabase
      .from('deadlines')
      .insert({
        case_id: deadline.case_id,
        key: deadline.key,
        due_at: deadline.due_at,
        source: deadline.source,
        rationale: deadline.rationale,
        label: deadline.label,
        consequence: deadline.consequence,
        auto_generated: deadline.auto_generated,
      })
      .select()
      .single()

    if (insertError || !inserted) {
      console.error(
        `[auto-generate-deadlines] Failed to insert ${deadline.key}:`,
        insertError?.message
      )
      continue
    }

    // --- Create reminders at -7d, -3d, -1d (skip past dates) ---
    const dueDate = new Date(deadline.due_at)
    const now = new Date()
    const remindersToInsert = [7, 3, 1]
      .map(
        (days) => new Date(dueDate.getTime() - days * 24 * 60 * 60 * 1000)
      )
      .filter((sendAt) => sendAt > now)
      .map((sendAt) => ({
        case_id: input.caseId,
        deadline_id: inserted.id,
        channel: 'email' as const,
        send_at: sendAt.toISOString(),
        status: 'scheduled' as const,
      }))

    if (remindersToInsert.length > 0) {
      await supabase.from('reminders').insert(remindersToInsert)
    }

    // --- Audit trail ---
    await supabase.from('task_events').insert({
      case_id: input.caseId,
      kind: 'deadline_auto_generated',
      payload: {
        deadline_id: inserted.id,
        key: deadline.key,
        label: deadline.label,
        due_at: deadline.due_at,
        trigger_task: input.taskKey,
      },
    })

    // --- In-app notification ---
    if (caseData?.user_id) {
      const formattedDate = new Date(deadline.due_at).toLocaleDateString(
        'en-US',
        {
          month: 'long',
          day: 'numeric',
          year: 'numeric',
        }
      )
      await supabase.from('notifications').insert({
        user_id: caseData.user_id,
        title: `${deadline.label} added`,
        body: `${deadline.label}: ${formattedDate}`,
        link: `/case/${input.caseId}/deadlines`,
        read: false,
      })
    }
  }
}
