/**
 * Auto-Generate Deadlines — DB Orchestrator
 *
 * Bridges the pure deadline-generator with the database. When a task is
 * completed, this function:
 *
 * 1. Fetches existing deadline keys for the case (deduplication)
 * 2. Calls generateDeadlines() (pure, no side effects)
 * 3. For each generated deadline: inserts via shared helper
 */

import { SupabaseClient } from '@supabase/supabase-js'
import { generateDeadlines } from '@lawyer-free/shared/rules/deadline-generator'
import { insertDeadlineWithReminders } from './insert-deadlines'

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface AutoGenerateInput {
  taskKey: string
  caseId: string
  completedAt: string
  taskMetadata: Record<string, unknown>
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export async function autoGenerateDeadlines(
  supabase: SupabaseClient,
  input: AutoGenerateInput
): Promise<void> {
  // 1. Fetch existing deadline keys for this case (deduplication)
  const { data: existingDeadlines } = await supabase
    .from('deadlines')
    .select('key')
    .eq('case_id', input.caseId)

  const existingKeys = (existingDeadlines ?? []).map(
    (d: { key: string }) => d.key
  )

  // 2. Generate deadlines via pure function
  const deadlines = generateDeadlines({
    taskKey: input.taskKey,
    caseId: input.caseId,
    completedAt: input.completedAt,
    taskMetadata: input.taskMetadata ?? {},
    existingDeadlineKeys: existingKeys,
  })

  if (deadlines.length === 0) return

  // 3. Fetch case owner once (used for notifications)
  const { data: caseData } = await supabase
    .from('cases')
    .select('user_id')
    .eq('id', input.caseId)
    .single()

  // 4. Insert each deadline via shared helper
  for (const deadline of deadlines) {
    await insertDeadlineWithReminders(supabase, deadline, {
      triggerSource: `task_completion:${input.taskKey}`,
      userId: caseData?.user_id,
    })
  }
}
