// Lookups must always be scoped by state — city names can collide across states.
export const CITY_COUNTY_MAP: Record<string, Record<string, string>> = {
  TX: {
    houston: "Harris",
    "san antonio": "Bexar",
    dallas: "Dallas",
    austin: "Travis",
    "fort worth": "Tarrant",
    "el paso": "El Paso",
    arlington: "Tarrant",
    "corpus christi": "Nueces",
    plano: "Collin",
    laredo: "Webb",
    lubbock: "Lubbock",
    garland: "Dallas",
    irving: "Dallas",
    frisco: "Collin",
    mckinney: "Collin",
    amarillo: "Potter",
    "grand prairie": "Dallas",
    brownsville: "Cameron",
    pasadena: "Harris",
    killeen: "Bell",
    mesquite: "Dallas",
    mcallen: "Hidalgo",
    carrollton: "Dallas",
    midland: "Midland",
    waco: "McLennan",
    denton: "Denton",
    abilene: "Taylor",
    "round rock": "Williamson",
    odessa: "Ector",
    richardson: "Dallas",
    tyler: "Smith",
    beaumont: "Jefferson",
    pearland: "Brazoria",
    "college station": "Brazos",
    "league city": "Galveston",
    "wichita falls": "Wichita",
    allen: "Collin",
    "sugar land": "Fort Bend",
    "the woodlands": "Montgomery",
    edinburg: "Hidalgo",
    lewisville: "Denton",
    mission: "Hidalgo",
    bryan: "Brazos",
    longview: "Gregg",
    temple: "Bell",
    "san marcos": "Hays",
    conroe: "Montgomery",
    "cedar park": "Williamson",
    "flower mound": "Denton",
    "new braunfels": "Comal",
    baytown: "Harris",
    harlingen: "Cameron",
    pharr: "Hidalgo",
    mansfield: "Tarrant",
    georgetown: "Williamson",
    "port arthur": "Jefferson",
    "north richland hills": "Tarrant",
    euless: "Tarrant",
    leander: "Williamson",
    grapevine: "Tarrant",
    bedford: "Tarrant",
    "haltom city": "Tarrant",
    desoto: "Dallas",
    pflugerville: "Travis",
    katy: "Harris",
    spring: "Harris",
    humble: "Harris",
    cypress: "Harris",
    "missouri city": "Fort Bend",
  },
  CA: {
    "los angeles": "Los Angeles",
    "san diego": "San Diego",
    "san jose": "Santa Clara",
    "san francisco": "San Francisco",
    fresno: "Fresno",
    sacramento: "Sacramento",
    "long beach": "Los Angeles",
    oakland: "Alameda",
    bakersfield: "Kern",
    anaheim: "Orange",
    "santa ana": "Orange",
    riverside: "Riverside",
    stockton: "San Joaquin",
    "chula vista": "San Diego",
    irvine: "Orange",
    fremont: "Alameda",
    "san bernardino": "San Bernardino",
    modesto: "Stanislaus",
    fontana: "San Bernardino",
    "moreno valley": "Riverside",
    glendale: "Los Angeles",
    "huntington beach": "Orange",
    "santa clarita": "Los Angeles",
    "garden grove": "Orange",
    oceanside: "San Diego",
    "rancho cucamonga": "San Bernardino",
    "santa rosa": "Sonoma",
    ontario: "San Bernardino",
    "elk grove": "Sacramento",
    corona: "Riverside",
    hayward: "Alameda",
    lancaster: "Los Angeles",
    palmdale: "Los Angeles",
    sunnyvale: "Santa Clara",
    pomona: "Los Angeles",
    escondido: "San Diego",
    torrance: "Los Angeles",
    pasadena: "Los Angeles",
    fullerton: "Orange",
    roseville: "Placer",
    visalia: "Tulare",
    concord: "Contra Costa",
    "el monte": "Los Angeles",
    "thousand oaks": "Ventura",
    "simi valley": "Ventura",
    salinas: "Monterey",
    "santa clara": "Santa Clara",
    oxnard: "Ventura",
    berkeley: "Alameda",
    ventura: "Ventura",
  },
  NY: {
    "new york": "New York",
    manhattan: "New York",
    brooklyn: "Kings",
    queens: "Queens",
    bronx: "Bronx",
    "staten island": "Richmond",
    buffalo: "Erie",
    rochester: "Monroe",
    yonkers: "Westchester",
    syracuse: "Onondaga",
    albany: "Albany",
    "new rochelle": "Westchester",
    "mount vernon": "Westchester",
    schenectady: "Schenectady",
    utica: "Oneida",
    "white plains": "Westchester",
    troy: "Rensselaer",
    "niagara falls": "Niagara",
    ithaca: "Tompkins",
    binghamton: "Broome",
    hempstead: "Nassau",
    flushing: "Queens",
    jamaica: "Queens",
    astoria: "Queens",
  },
  FL: {
    jacksonville: "Duval",
    miami: "Miami-Dade",
    tampa: "Hillsborough",
    orlando: "Orange",
    "st. petersburg": "Pinellas",
    "st petersburg": "Pinellas",
    hialeah: "Miami-Dade",
    tallahassee: "Leon",
    "port st. lucie": "St. Lucie",
    "port st lucie": "St. Lucie",
    "cape coral": "Lee",
    "fort lauderdale": "Broward",
    "pembroke pines": "Broward",
    hollywood: "Broward",
    miramar: "Broward",
    gainesville: "Alachua",
    "coral springs": "Broward",
    clearwater: "Pinellas",
    "miami gardens": "Miami-Dade",
    "palm bay": "Brevard",
    "pompano beach": "Broward",
    "west palm beach": "Palm Beach",
    lakeland: "Polk",
    davie: "Broward",
    "miami beach": "Miami-Dade",
    sunrise: "Broward",
    plantation: "Broward",
    "boca raton": "Palm Beach",
    deltona: "Volusia",
    largo: "Pinellas",
    "deerfield beach": "Broward",
    melbourne: "Brevard",
    "fort myers": "Lee",
    "daytona beach": "Volusia",
    kissimmee: "Osceola",
    "north miami": "Miami-Dade",
    homestead: "Miami-Dade",
    pensacola: "Escambia",
    ocala: "Marion",
    "boynton beach": "Palm Beach",
    lauderhill: "Broward",
    "palm coast": "Flagler",
  },
  PA: {
    philadelphia: "Philadelphia",
    pittsburgh: "Allegheny",
    allentown: "Lehigh",
    erie: "Erie",
    reading: "Berks",
    scranton: "Lackawanna",
    bethlehem: "Northampton",
    lancaster: "Lancaster",
    harrisburg: "Dauphin",
    altoona: "Blair",
    york: "York",
    "wilkes-barre": "Luzerne",
    "wilkes barre": "Luzerne",
    chester: "Delaware",
    easton: "Northampton",
    norristown: "Montgomery",
    levittown: "Bucks",
    hazleton: "Luzerne",
    mckeesport: "Allegheny",
    "state college": "Centre",
    johnstown: "Cambria",
  },
};
