import { NextRequest, NextResponse } from 'next/server'
import { getAuthenticatedClient } from '@/lib/supabase/route-handler'
import { autoGenerateDeadlines } from '@/lib/rules/auto-generate-deadlines'
import { seedDeadlinesFromDates } from '@lawyer-free/shared/rules/deadline-generator'
import { insertDeadlineWithReminders } from '@/lib/rules/insert-deadlines'

/**
 * POST /api/cases/[id]/deadlines/backfill
 *
 * Scans completed tasks for the case and generates any missing deadlines.
 * Also checks welcome task metadata for filing_date / service_date.
 */
export async function POST(
  _request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params
    const auth = await getAuthenticatedClient()
    if (!auth.ok) return auth.error
    const { supabase } = auth

    // 1. Verify case ownership and get dispute_type
    const { data: caseData, error: caseError } = await supabase
      .from('cases')
      .select('id, dispute_type, user_id')
      .eq('id', id)
      .single()

    if (caseError || !caseData) {
      return NextResponse.json(
        { error: 'Case not found' },
        { status: 404 }
      )
    }

    let deadlinesCreated = 0

    // 2. Scan completed tasks and generate deadlines for each
    const { data: completedTasks } = await supabase
      .from('tasks')
      .select('task_key, completed_at, metadata')
      .eq('case_id', id)
      .eq('status', 'completed')

    for (const task of completedTasks ?? []) {
      if (!task.completed_at) continue
      await autoGenerateDeadlines(supabase, {
        taskKey: task.task_key,
        caseId: id,
        completedAt: task.completed_at,
        taskMetadata: (task.metadata as Record<string, unknown>) ?? {},
      })
    }

    // 3. Check welcome task metadata for filing_date / service_date
    const { data: welcomeTask } = await supabase
      .from('tasks')
      .select('metadata')
      .eq('case_id', id)
      .eq('task_key', 'welcome')
      .maybeSingle()

    const meta = (welcomeTask?.metadata ?? {}) as Record<string, unknown>
    const filingDate = meta.filing_date as string | undefined
    const serviceDate = meta.service_date as string | undefined

    if (filingDate || serviceDate) {
      // Fetch existing deadline keys for dedup
      const { data: existingDeadlines } = await supabase
        .from('deadlines')
        .select('key')
        .eq('case_id', id)

      const existingKeys = (existingDeadlines ?? []).map(
        (d: { key: string }) => d.key
      )

      // Resolve business sub-type if needed
      let businessSubType: string | undefined
      if (caseData.dispute_type === 'business') {
        const { data: bizDetails } = await supabase
          .from('business_details')
          .select('business_sub_type')
          .eq('case_id', id)
          .maybeSingle()
        businessSubType = bizDetails?.business_sub_type ?? undefined
      }

      const seeded = seedDeadlinesFromDates({
        caseId: id,
        disputeType: caseData.dispute_type ?? 'other',
        businessSubType,
        filingDate,
        serviceDate,
        existingDeadlineKeys: existingKeys,
      })

      for (const deadline of seeded) {
        const insertedId = await insertDeadlineWithReminders(
          supabase,
          deadline,
          { triggerSource: 'backfill', userId: caseData.user_id }
        )
        if (insertedId) deadlinesCreated++
      }
    }

    return NextResponse.json({ success: true, deadlinesCreated })
  } catch {
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    )
  }
}
